# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.02
default_acceleration_scaling_factor: 0.01

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_a1:
    min_position: !degrees -170.0
    max_position: !degrees 170.0
    has_velocity_limits: true
    max_velocity: 9.250245035569947
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a2:
    min_position: !degrees -170.0
    max_position: !degrees 50.0
    has_velocity_limits: true
    max_velocity: 9.232791743050003
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a3:
    min_position: !degrees -110.0
    max_position: !degrees 155.0
    has_velocity_limits: true
    max_velocity: 9.389871375729493
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a4:
    min_position: !degrees -175.0
    max_position: !degrees 175.0
    has_velocity_limits: true
    max_velocity: 10.47197551196598
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a5:
    min_position: !degrees -120.0
    max_position: !degrees 120.0
    has_velocity_limits: true
    max_velocity: 10.47197551196598
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a6:
    min_position: !degrees -350.0
    max_position: !degrees 350.0
    has_velocity_limits: true
    max_velocity: 13.96263401595464
    has_acceleration_limits: false
    max_acceleration: 0
